/**
 * Preset that controls quality and optional target size behavior for compression.
 */
export interface CompressionPreset {
  /** Human-readable preset name. */
  name: string;
  /** Quality level from 1-100 (higher means better quality and larger files). */
  quality: number;
  /** Optional target size in bytes to aim for. */
  targetSizeBytes?: number;
}

/**
 * Target size request that can be defined in bytes, kilobytes, or megabytes.
 */
export interface TargetSize {
  /** Numeric target amount. */
  value: number;
  /** Unit for the target size. */
  unit: "b" | "kb" | "mb";
}

/**
 * File types that SquishCLI can route to dedicated compressors.
 */
export type SupportedFileType = "image" | "pdf";

/**
 * One compression unit of work generated by CLI parsing.
 */
export interface CompressionJob {
  /** Absolute or relative input path. */
  inputPath: string;
  /** Optional output path. If omitted, compressor decides a default path. */
  outputPath?: string;
  /** Resolved file type for routing. */
  fileType: SupportedFileType;
  /** Compression preset to apply. */
  preset: CompressionPreset;
}

/**
 * Result payload returned by format-specific compressors.
 */
export interface CompressionResult {
  /** Original input path. */
  inputPath: string;
  /** Produced output path. */
  outputPath: string;
  /** Whether compression succeeded. */
  success: boolean;
  /** Input file size in bytes (if known). */
  originalSizeBytes?: number;
  /** Output file size in bytes (if known). */
  compressedSizeBytes?: number;
  /** Optional error details for failures. */
  error?: string;
}
